## 1. Creating NumPy Arrays and Array Information

In [1]:
import numpy as np

In [7]:
numbers = np.array([10, 20, 30, 40, 50])
print(numbers)
print(numbers.shape)
print(numbers.size)
print(numbers.dtype)

[10 20 30 40 50]
(5,)
5
int64


In [8]:
marks = np.array([65, 70, 85, 90, 55])
print(marks)
print(marks.shape)
print(marks.size)
print(marks.dtype)

[65 70 85 90 55]
(5,)
5
int64


In [9]:
matrix = np.array([[1,2,3],[3,2,1]])
print(matrix)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)

[[1 2 3]
 [3 2 1]]
(2, 3)
6
int64


## 2. Indexing

In [12]:
num = np.array([10, 20, 30, 40, 50])
print(num[0])
print(num[2])
print(num[4])

10
30
50


In [14]:
matrix = np.array([[1,2,3],[3,2,1]])
print(matrix[0][0])
print(matrix[1][2])

1
1


## 3. Slicing

In [18]:
num = np.array([10, 20, 30, 40, 50])
print(num[0:3])

[10 20 30]


In [19]:
num = np.array([10, 20, 30, 40, 50])
print(num[1:4])

[20 30 40]


In [21]:
num = np.array([10, 20, 30, 40, 50])
print(num[2:])

[30 40 50]


In [22]:
num = np.array([10, 20, 30, 40, 50])
print(num[3:])

[40 50]


In [23]:
num = np.array([10, 20, 30, 40, 50])
print(num[:3])

[10 20 30]


In [24]:
num = np.array([10, 20, 30, 40, 50])
print(num[:])

[10 20 30 40 50]


## 4. Statistical Functions

In [25]:
marks = np.array([65, 70, 85, 90, 55])

In [26]:
print(sum(marks))

365


In [29]:
print(max(marks))

90


In [30]:
print(min(marks))

55


In [32]:
print(np.mean(marks))

73.0


In [33]:
print(np.std(marks))

12.884098726725126


In [38]:
print(np.median(marks))

70.0


## 5. Reshape

In [43]:
num = np.array([1, 2, 3, 4, 5, 6])

In [44]:
new_2D = num.reshape(2,3)
print(new_2D)

[[1 2 3]
 [4 5 6]]


In [45]:
new_3D = num.reshape(3,2)
print(new_3D)

[[1 2]
 [3 4]
 [5 6]]


## 6. Power Functions

In [46]:
square = np.square(5)
print(square)

25


In [47]:
sqrt = np.sqrt(25)
print(sqrt)

5.0


In [48]:
pow = np.pow(5,2)
print(pow)

25
